### ISSUE TITLE
Broken rendering of lower tabs in new version

### ISSUE THREAD

**Issue by DoctorMeta** [gbl/AdvancementInfo#10]
![image](https://user-images.githubusercontent.com/86451288/142987951-300ad8aa-a30c-4b26-9b2e-189a6e18bd43.png)
In the new 1.17.1-fabric0.36.1-1.2.2, the rendering of lower tabs is quite interesting, they actually work if you click on them, it's just that they're in the wrong place.

![image](https://user-images.githubusercontent.com/86451288/142988457-489bb39d-558f-428e-841e-2f780dae37c8.png)
In the older 1.17.1-fabric0.36.1-1.2.1. this issue doesn't exist.

**Comment by gbl** [comment]
Thanks for noticing this! Should be fixed in version 1.3 which I just published. If not, feel free to reopen.
