### ISSUE TITLE
[Feature / Issue] Overriding the limit of the number of the tabs

### ISSUE THREAD

**Issue by Wajiro** [gbl/AdvancementInfo#16]
Any hope for an update overriding the 26-tab limit, like what [Moar Advancements](https://www.curseforge.com/minecraft/mc-mods/moaradvancements) did on forge? (cuz such thing hasn't ever been done for Fabric yet)

**Comment by Wajiro** [comment]
Update: every time I search a keyword (in the upper-left search box) from the advancement tabs that are 'covered' behind the limit (and are inaccessible), the game freezes until crashing.

**Comment by gbl** [comment]
Sorry, but won't happen anytime soon unless someone implements it and sends me a pull request. I haven't played Minecraft since version 1.16, and while I've been updating my mods until now, I won't be adding new features.

**Comment by Wajiro** [comment]
Well, at least the "Achievement Plates" mod could be a tracking workaround. Thx for responding
