### ISSUE TITLE
Two by Two progress shows item names, not mob names

### ISSUE THREAD

**Issue by clarfonthey** [gbl/AdvancementInfo#18]
Specifically, it displays "Raw Chicken" and "Raw Rabbit" as two mobs needing to be bred, instead of Chicken and Rabbit. This isn't an issue for other mobs, who correctly show their names.

**Comment by Jackuhlf** [comment]
because those mobs have food with the same name as the mob. it happens for a few advancements

**Comment by gbl** [comment]
Yes, that's unfortunate, but I can't do much unless I make special cases for each advancement, which will in turn break when a new MC version adds or removes or renames them. The advancements themselves have entries like "chicken", but no hint if a chicken (animal) or chicken (item) is wanted, so I just try a few possiblities until I find one.
