### ISSUE TITLE
Update to 1.20.1 please

### ISSUE THREAD

**Issue by davepusey** [gbl/AdvancementInfo#38]
Update to 1.20.1 please.

**Comment by Borbarad2** [comment]
yes, please

**Comment by gbl** [comment]
Done, I released a version for 1.20 and 1.20.1

**Comment by Borbarad2** [comment]
Thanks, i saw it and download it from curseforge, but it is the same version for 1.20. and if i tried out for 1.20.1 it breaks the game and does not start.

**Comment by gbl** [comment]
@Borbarad2, I checked it and the 1.20 version works for me on 1.20.1.

**Comment by Borbarad2** [comment]
Thank you again. 
Each time I load the mod, the game break, i.e does not start proberly, it goes on Exit, and say it is not compatible with the setup. Does not matter if i try 1.20 or 1.20.1. I don't know what is wrong, but i still try to find out and load your mod in again. 
This is mine error messages: 
![grafik](https://github.com/gbl/AdvancementInfo/assets/105346182/07ca8b7f-c70d-4512-b32f-bb1254c206d5)

Thanks for your help anyway. 
Thank you for the update, it is greatly appreciated.

P.S: It seems something is wrong with the cloth-config. I tried different/newest  and compatible(1.20.1) Version of it but all are broken and your mod seems to need that cloth-config mod aprior.

**Comment by davepusey** [comment]
Just tested, and it's working fine for me on 1.20.1

Thank you for the update, it is greatly appreciated.

**Comment by Borbarad2** [comment]
> Just tested, and it's working fine for me on 1.20.1
> 
> Thank you for the update, it is greatly appreciated.

How does it work at yours? You need the newest version of [cloth-api-4.0.65.jar] in atleast version 5.0.0 in a 1.20.1 compatible version, which is not available yet, or where do you get it from?

**Comment by Borbarad2** [comment]
Thanks for help and updating.
Now it is working fine.
