### ISSUE TITLE
failed to load

### ISSUE THREAD

**Issue by tim14hall** [gbl/AdvancementInfo#4]
Could not find required mod: advancementinfo requires {fabric @ [*]}
Creating Empty clause ?
[2021-03-01-7.log.gz](https://github.com/gbl/AdvancementInfo/files/6061764/2021-03-01-7.log.gz)

**Comment by gbl** [comment]
You need the Fabric API as well (like for almost all mods), from https://modrinth.com/mod/fabric-api/versions or  https://www.curseforge.com/minecraft/mc-mods/fabric-api/files (make sure you download the correct version for your Minecraft).
