### ISSUE TITLE
Version 1.4 being treated as a downgrade by Prism Launcher

### ISSUE THREAD

**Issue by BlueJayofEvil** [gbl/AdvancementInfo#41]
I'm not sure if this should be reported as a bug in Prism Launcher or here, but it seems due to AdvancementInfo v1.4 being marked as 1.20 (instead of 1.20-1.20.1) it is being treated as an 'older' release by the auto-updater. If AdvancementInfo 1.4 is installed, the auto-updater tries to "upgrade" it to v1.3.1 (which is the actual older version).
A simple marking of it being 1.20.1 compatible on Modrinth/Curseforge should fix this, but I'm not sure if this should also be reported to Prism Launcher as well?

**Comment by gbl** [comment]
Marked 1.4 as MC 1.20.1 as well as 1.20, hope that helps!

**Comment by BlueJayofEvil** [comment]
Confirmed this fixed the issue. Thanks!
